#!/usr/bin/env python3
"""Extract glyph outlines from Latin Modern Roman into MoonBit data.

Reads /usr/share/texmf/fonts/opentype/public/lm/lmroman10-regular.otf
(CFF cubic outlines), normalizes to 1em units (y-up, baseline at y=0),
and writes tex/glyphs_data.mbt. Latin Modern is distributed under the
GUST Font License; see docs/porting.md.

Usage: python3 tools/extract_glyphs.py  (requires fontTools)
"""

from fontTools.ttLib import TTFont
from fontTools.pens.recordingPen import RecordingPen

FONT_PATH = "/usr/share/texmf/fonts/opentype/public/lm/lmroman10-regular.otf"
# Fallback for glyphs the text font lacks (Greek letters): the math font
# of the same family.
FALLBACK_FONT_PATH = (
    "/usr/share/texmf/fonts/opentype/public/lm-math/latinmodern-math.otf"
)
OUT_PATH = "tex/glyphs_data.mbt"

# Glyph subset: digits, latin letters, the Greek letters MiniTex supports,
# and common formula punctuation. Anything else falls back to the
# placeholder box at layout time.
CHARS = (
    "0123456789"
    "abcdefghijklmnopqrstuvwxyz"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "αβγδεθλμπσφω"
    "+-=(),./"
)

HEADER = """// Code generated by tools/extract_glyphs.py from Latin Modern Roman 10
// (lmroman10-regular.otf, GUST Font License — see docs/porting.md).
// DO NOT EDIT. Coordinates are in 1em units, y-up, baseline at y = 0.

///|
/// Outline and advance of an embedded glyph, or `None` if the character
/// is outside the embedded subset (callers fall back to placeholder boxes).
fn glyph_data(c : Char) -> GlyphData? {
  match c {
"""

FOOTER = """    _ => None
  }
}
"""


def fmt(x):
    s = f"{x:.4f}".rstrip("0").rstrip(".")
    if s in ("", "-0"):
        return "0"
    return s


def main():
    # (font, cmap, glyph_set, units_per_em) per source, tried in order.
    sources = []
    for path in (FONT_PATH, FALLBACK_FONT_PATH):
        font = TTFont(path)
        sources.append(
            (font.getBestCmap(), font.getGlyphSet(), font["head"].unitsPerEm)
        )

    arms = []
    for ch in CHARS:
        found = None
        for cmap, glyph_set, upem in sources:
            name = cmap.get(ord(ch))
            if name is not None:
                found = (glyph_set, upem, name)
                break
        if found is None:
            print(f"warning: no glyph for {ch!r}, skipped")
            continue
        glyph_set, upem, name = found
        pen = RecordingPen()
        glyph_set[name].draw(pen)
        segs = []
        for op, args in pen.value:
            pts = [
                (x / upem, y / upem) for pt in args for (x, y) in [pt]
            ]
            if op == "moveTo":
                segs.append(f"M({fmt(pts[0][0])}, {fmt(pts[0][1])})")
            elif op == "lineTo":
                segs.append(f"L({fmt(pts[0][0])}, {fmt(pts[0][1])})")
            elif op == "curveTo":
                flat = ", ".join(f"{fmt(x)}, {fmt(y)}" for x, y in pts)
                segs.append(f"C({flat})")
            elif op in ("closePath", "endPath"):
                segs.append("Z")
            else:
                raise ValueError(f"unexpected op {op}")
        adv = glyph_set[name].width / upem
        lit = ch if ch not in ("'", "\\") else "\\" + ch
        arms.append(
            f"    '{lit}' => Some({{ adv: {fmt(adv)}, segs: [{', '.join(segs)}] }})"
        )

    with open(OUT_PATH, "w") as f:
        f.write(HEADER)
        f.write("\n".join(arms))
        f.write("\n")
        f.write(FOOTER)
    print(f"wrote {OUT_PATH}: {len(arms)} glyphs")


if __name__ == "__main__":
    main()
